[build]
  edge_functions = "netlify/edge-functions"

[build.environment]
  NODE_VERSION = "24"

[[edge_functions]]
  path = "/*"
  function = "netlify"
  import_map = "./netlify/edge-functions/import_map.json"
